#!/bin/sh

lb config noauto \
--architecture amd64 \
--archive-areas "main contrib non-free" \
--binary-filesystem ext4 \
--binary-image iso \
--debconf-frontend noninteractive \
--debootstrap-options "--variant=minbase" \
--debian-installer cdrom \
--debian-installer-distribution bullseye \
--debian-installer-gui false \
--distribution-binary bullseye \
--distribution-chroot bullseye \
--firmware-binary true \
--firmware-chroot true \
--linux-package "linux-image linux-headers" \
--mode debian \
--system normal \
--bootloaders grub-efi \
--interactive false

"${@}"
